apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-shachar
spec:
  containers:
  - name: use-pv
    image: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
    volumeMounts:
    - name: pv-1
      mountPath: /data
  volumes:
  - name: pv-1
    emptyDir: {}
status: {}
