apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template: 
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: kodekloud/webapp-color
        ports:
        - containerPort: 80

