#I used the minikube so initially i tried to create it on 'kubernetes.io/hostname: minikube' and then changed the node name to 'nodeName: nginxnode' in the yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  nodeSelector:
    nodeName: nginxnode
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
