#I used the minikube so initially i tried to create it on minikube and then changed the node name to ''worker' in the yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  nodeSelector:
    kubernetes.io/hostname: worker
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
